---
title: "Data ETL: TEC"
author: "Florian Mayer, DBCA"
date: "`r Sys.time()`"
always_allow_html: yes
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# devtools::install_github("ropenscilabs/skimr")
# devtools::install_github("tidyverse/readr")
# install from github: "brianb/mdbtools"
# devtools::install_github("ropensci/ckanr")
library(tidyverse)
library(skimr)
library(leaflet)
library(Hmisc)
library(ckanr)

# Configure ckanr to data.dpaw.wa.gov.au
ckanr::ckanr_setup(url = Sys.getenv("CKAN_URL"), 
                   key = Sys.getenv("CKAN_API_KEY"))

#' Download, extract and open a zipped Access database from a CKAN dataset
#' 
#' @param resource_id The CKAN resource ID of a zipped Access DB
#' @param destdir The local destination directory for the extracted file, 
#'  will be created if not existing. Default: "data"
#' @param dateformat The parameter dateformat for Hmisc::mdb.get(), 
#'  default: '%Y-%m-%d'
#' @param asis The parameter as.is for Hmisc::mdb.get(), default: TRUE
#' @returns The Hmisc::mdb.get connection
dl_mdbzip <- function(resource_id, 
                      destdir="data", 
                      dateformat = '%Y-%m-%d', 
                      asis = TRUE) {
    dir.create(file.path(getwd(), destdir), showWarnings = FALSE)
    tmp <- tempfile()
    res_url <- ckanr::resource_show(resource_id)$url
    utils::download.file(res_url, tmp)
    dbfile <- utils::unzip(tmp, exdir = destdir)
    unlink(tmp)
    con <- Hmisc::mdb.get(dbfile, dateformat = dateformat, as.is = asis)
    con
}
```
# SCB data background
[TEC dataset](https://data.dpaw.wa.gov.au/dataset/threatened-ecological-communities-database)
on the [departmental data catalogue](https://data.dpaw.wa.gov.au/).

# TEC

## TEC data load
```{r tec_data_load}
tec <- dl_mdbzip("598b1e70-5707-4dbc-a665-1189e1524ebe")
# tec_app <- dl_mdbzip("27d9b026-6933-4516-acf6-41edc6134adb")
```

### Helpers
```{r helpers}
# Date conventions
orders <- c("mdyHMS")
tz <- "Australia/Perth"

# Prepare column def
as_def <- . %>% paste(., "=", ., " %>% as.character, \n")
make_coldef <- . %>% names %>% purrr::map(as_def) %>% unlist %>% cat
```

## Communities
```{r communities}
former_range <- tec$FORMER_RANGES %>%
  dplyr::transmute(
    former_range_id = FORMER.RANGE %>% as.character(),
    former_range = FORMER.RANGE.DESC %>% as.character()
  )
# make_coldef(former_range)

range_decline <- tec$RANGE_DECLINE %>%
    dplyr::transmute(
        range_decline_id = RANGE.DECLINE  %>% as.integer(), 
        range_decline = RANGE.DECLINE.DESC  %>% as.character()
    )
# make_coldef(range_decline)

occurrence_decline <- tec$OCCURRENCES_DECLINE %>%
    dplyr::transmute(
        occurrence_decline_id = OCC.DECLINE  %>% as.integer(), 
        occurrence_decline = OCC.DECLINE.DESC  %>% as.character()
    )
# make_coldef(occurrence_decline)

communities <- tec$COMMUNITIES %>%
    tibble::as.tibble() %>%
  dplyr::transmute(
    community_id = COM.NO %>% as.integer(),
    community_label = COM.ID %>% as.character(),
    community_name = COM.NAME %>% as.character(),
    community_description = COM.DESC %>% as.character(),
    former_range_id = COM.FORMER.RANGE %>% as.character(),
    range_decline_id = COM.RANGE.DECLINE %>% as.integer(),
    occurrence_decline_id = COM.OCC.DECLINE %>% as.integer(),
    community_tec_listing = COM.TEC.LISTING %>% as.integer(),
    community_original_area = COM.ORIG.AREA %>% as.double(),
    community_area_accuracy = COM.AREA.ACC %>% as.double(),
    preliminary = COM.PRELIMINARY %>% as.character(),
    status = COM.STATUS %>% as.character()
  ) %>%
  dplyr::left_join(former_range, by = "former_range_id") %>%
  dplyr::left_join(range_decline, by = "range_decline_id") %>%
  dplyr::left_join(occurrence_decline, by = "occurrence_decline_id")
# make_coldef(communities)
communities %>% skim()
communities %>% DT::datatable(.)
```

## Occurrences
```{r occurrences}
occurrences <- tec$OCCURRENCES %>% 
    tibble::as.tibble() %>%
    dplyr::transmute(
    id = OCC.UNIQUE.ID %>% as.integer,
    com_no = COM.NO %>% as.integer,
    occ_no = OCC.NO %>% as.integer,
    confidential = OCC.CONFIDENTIAL %>% as.integer,
    source_code = OCC.SOURCE.CODE %>% as.character,
    body_id = BDY.ID %>% as.integer,
    br_code = OCC.BR.CODE %>% as.character,
    beard_dist_code = OCC.BEARD.DIST.CODE %>% as.character,
    ibra_reg_code = OCC.IBRA.REG.CODE %>% as.character,
    dola_ref = OCC.DOLA.REF %>% as.character,
    ctrc_sys = OCC.CTRC.SYS %>% as.integer,
    ctrc_recommendation = OCC.CTRC.RECOMMENDATION %>% as.character,
    cwealth_listing = OCC.CWEALTH.LISTING %>% as.character,
    original_area = OCC.ORIGINAL.AREA %>% as.double,
    area_accuracy = OCC.AREA.ACCURACY %>% as.double,
    data = OCC.DATA %>% as.character,
    other = OCC.OTHER %>% as.character,
    soil = OCC.SOIL %>% as.character,
    surf_geology = OCC.SURF.GEOLOGY %>% as.character,
    land_element = OCC.LAND.ELEMENT %>% as.character,
    water = OCC.WATER %>% as.character,
    drainage = OCC.DRAINAGE %>% as.character,
    com_structure = OCC.COM.STRUCTURE %>% as.character,
    classification = OCC.CLASSIFICATION %>% as.character,
    other_attr =  OCC.OTHER.ATTR %>% as.character,
    beard_map_code = OCC.BEARD.MAP.CODE %>% as.character,
    beard_desc = OCC.BEARD.DESC %>% as.character,
    desc = OCC.DESC %>% as.character,
    boundary_desc = OCC.BOUNDARY.DESC %>% as.character,
    species_desc = OCC.SPECIES.DESC %>% as.character,
    zone_code = OCC.ZONE.CODE %>% as.character,
    username = USERNAME %>% as.character,
    date_entered =  OCC.DATE.ENTERED %>% 
        lubridate::parse_date_time(., orders = orders, tz=tz), 
    date_edited = OCC.DATE.EDITED %>% as.character %>% 
        lubridate::parse_date_time(., orders = orders, tz=tz),
    buffer_radius = OCC.BUFFER.RADIUS %>% as.integer,
    bush_forever_site_no = OCC.BUSH.FOREVER.SITE.NO %>% as.integer,
    status_code = OCC.STATUS.CODE %>% as.logical,
    no_boundary = OCC.NO.BOUNDARY %>% as.integer,
    commenwealth_desc = OCC.COMMONWEALTH.DESC %>% as.character
    )
occurrences %>% skimr::skim()
occurrences %>% head(10) %>% DT::datatable(.)
```

## TEC data upload
Create resource once-off to get a resource ID.
Subsequently, upload the compiled workbook.
Note, this process lags one compilation of this workbook, as the HTML output
is generated after the R code is run.

```{r tec_upload}
# d <- ckanr::package_show("threatened-ecological-communities-database")

etl_fn <- "data_etl_tec.html"
etl_title <- "TEC Data ETL"
# r <- ckanr::resource_create(package_id = d$id, format = "html", name = etl_title, upload = etl_fn)
ckanr::resource_update("80009375-19e2-45d3-a1ae-068143fa03a5", etl_fn)

com_fn <- "data/communities.csv"
communities %>% write_delim(com_fn, delim = ",")
com_title <- "Threatened Ecological Communities"
# r <- ckanr::resource_create(package_id = d$id, format = "csv", name = com_title, upload = com_fn)
ckanr::resource_update("9782cc52-7be8-494a-a7da-51845c119a21", com_fn)

occ_fn <- "data/occurrences.csv"
occurrences %>% write_delim(occ_fn, delim = ",")
off_title <- "Threatened Ecological Community Occurrences"
# r <- ckanr::resource_create(package_id = d$id, format = "csv", name = occ_title, upload = occ_fn)
ckanr::resource_update("65f43392-a8c5-41e2-a31e-cc4135e9274e", occ_fn)

```
