---
title: "Report TFA-TSC: Fauna"
author: "Camilla Piggott, DBCA"
date: "`r Sys.time()`"
always_allow_html: yes
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    fig_width: 10
    fig_height: 6
    code_folding: hide
    theme: lumen
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = TRUE)
source("helpers.R")
```

# Context
[Fauna dataset](https://data.dpaw.wa.gov.au/dataset/threatened-and-priority-fauna-database) 
on the [departmental data catalogue](https://data.dpaw.wa.gov.au/).

[TSC Fauna database](https://tsc.dbca.wa.gov.au/species/?paraphyletic_groups=20&is_terminal_taxon=true) 
on the [TSC catalogue](https://tsc.dbca.wa.gov.au/).

The code for all SCB workbooks is under version control at [github](https://github.com/dbca-wa/scarab-scripts).

```{r read in tfa data}
tfa_data<- here::here("data","fauna_cons_listing.csv") %>%
  readr::read_csv(col_types = cols(
      list_code = col_character(),
      criteria_code = col_character(),
      name_id = col_character()))
```

##  Check unique number of species and conservation criteria

```{r uniqueness in data}
species_unique<-unique(tfa_data$species_code) #1004
scientific_name_unique<-unique(tfa_data$scientific_name) #1004
category_code_unique<-unique(tfa_data$category_code) #27
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
